# Generated by Django 5.1 on 2024-08-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recent', '0002_recentlyplayed_played_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentlyplayed',
            name='created_at',
        ),
    ]
