# Generated by Django 5.1 on 2024-09-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recent', '0003_remove_recentlyplayed_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyplayed',
            name='play_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
