# Generated by Django 5.1 on 2024-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedartist',
            name='user',
        ),
        migrations.AlterField(
            model_name='likedartist',
            name='artist_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
