# Generated by Django 5.1 on 2024-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_likedartist_user_alter_likedartist_artist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_image', models.URLField()),
                ('spotify_uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LikedArtist',
        ),
    ]
