# Generated by Django 5.1 on 2024-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
