# Generated by Django 5.1 on 2024-09-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0002_alter_song_album_alter_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='track_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
