# Generated by Django 5.1 on 2024-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0003_song_album_cover_url_song_popularity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spotify_url',
            new_name='spotify',
        ),
        migrations.AddField(
            model_name='song',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
