# Generated by Django 5.1 on 2024-09-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0004_rename_title_song_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
