# Generated by Django 5.1 on 2024-08-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyToken',
            new_name='TokenTable',
        ),
    ]
